import { AutomationNodeDef } from "@/types/automation";

export const NODE_DEFINITIONS: AutomationNodeDef[] = [
  // ── TRIGGERS ────────────────────────────────────────────────
  {
    type: "trigger_upload",
    category: "trigger",
    label: "File Upload",
    description: "Start workflow when a file is uploaded",
    icon: "⬆️",
    color: "emerald",
    inputs: 0,
    outputs: 1,
    fields: [
      {
        key: "fileTypes",
        label: "Allowed File Types",
        type: "text",
        placeholder: "image/*, application/pdf",
        defaultValue: "image/*",
        description: "MIME types separated by comma",
      },
      {
        key: "maxSizeMb",
        label: "Max File Size (MB)",
        type: "number",
        defaultValue: 10,
      },
    ],
  },
  {
    type: "trigger_webhook",
    category: "trigger",
    label: "Webhook",
    description: "Trigger via HTTP POST request",
    icon: "🔗",
    color: "emerald",
    inputs: 0,
    outputs: 1,
    fields: [
      {
        key: "method",
        label: "HTTP Method",
        type: "select",
        options: [
          { label: "POST", value: "POST" },
          { label: "GET", value: "GET" },
        ],
        defaultValue: "POST",
      },
      {
        key: "authToken",
        label: "Auth Token (optional)",
        type: "text",
        placeholder: "Bearer token...",
      },
    ],
  },
  // ── AI NODES ────────────────────────────────────────────────
  {
    type: "ai_nvidia_nim",
    category: "ai",
    label: "NVIDIA NIM",
    description: "Run inference using NVIDIA NIM models",
    icon: "⚡",
    color: "green",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [
          { label: "LLaMA 3.1 8B Instruct", value: "meta/llama-3.1-8b-instruct" },
          { label: "GPT-OSS 20B", value: "openai/gpt-oss-20b" },
          { label: "GPT-OSS 120B", value: "openai/gpt-oss-120b" },
          { label: "Mistral 7B Instruct", value: "mistralai/mistral-7b-instruct-v0.3" },
          { label: "Phi-3 Mini", value: "microsoft/phi-3-mini-128k-instruct" },
        ],
        defaultValue: "meta/llama-3.1-8b-instruct",
        required: true,
      },
      {
        key: "systemPrompt",
        label: "System Prompt",
        type: "textarea",
        placeholder: "You are a helpful assistant...",
        description: "Instructions for the AI model",
      },
      {
        key: "userMessage",
        label: "User Message / Prompt",
        type: "textarea",
        placeholder: "Use {{input}} to reference input data...",
        defaultValue: "{{input}}",
        required: true,
        description: "Use {{input}} for previous node output",
      },
      {
        key: "temperature",
        label: "Temperature",
        type: "number",
        defaultValue: 0.7,
        description: "0 = deterministic, 1 = creative",
      },
      {
        key: "maxTokens",
        label: "Max Output Tokens",
        type: "number",
        defaultValue: 1024,
      },
      {
        key: "responseFormat",
        label: "Response Format",
        type: "select",
        options: [
          { label: "Plain Text", value: "text" },
          { label: "JSON Object", value: "json" },
        ],
        defaultValue: "text",
      },
    ],
  },
  {
    type: "ai_openai",
    category: "ai",
    label: "AI Model (OpenAI)",
    description: "Use OpenAI GPT models for text generation",
    icon: "🤖",
    color: "violet",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [
          { label: "GPT-4o", value: "gpt-4o" },
          { label: "GPT-4o Mini", value: "gpt-4o-mini" },
          { label: "GPT-4 Turbo", value: "gpt-4-turbo" },
          { label: "GPT-3.5 Turbo", value: "gpt-3.5-turbo" },
        ],
        defaultValue: "gpt-4o-mini",
        required: true,
      },
      {
        key: "systemPrompt",
        label: "System Prompt",
        type: "textarea",
        placeholder: "You are a helpful assistant...",
      },
      {
        key: "userMessage",
        label: "User Message",
        type: "textarea",
        placeholder: "Use {{input}} to reference input data...",
        defaultValue: "{{input}}",
        required: true,
      },
      {
        key: "temperature",
        label: "Temperature",
        type: "number",
        defaultValue: 0.7,
      },
      {
        key: "maxTokens",
        label: "Max Output Tokens",
        type: "number",
        defaultValue: 1024,
      },
      {
        key: "responseFormat",
        label: "Response Format",
        type: "select",
        options: [
          { label: "Plain Text", value: "text" },
          { label: "JSON Object", value: "json" },
        ],
        defaultValue: "text",
      },
    ],
  },
  {
    type: "ai_text_extract",
    category: "ai",
    label: "Text Extraction (OCR)",
    description: "Extract text from images using AI vision",
    icon: "🔍",
    color: "blue",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "model",
        label: "Vision Model",
        type: "select",
        options: [
          { label: "NVIDIA NIM Vision", value: "nvidia/llama-3.2-11b-vision-instruct" },
          { label: "GPT-4o Vision", value: "gpt-4o" },
        ],
        defaultValue: "nvidia/llama-3.2-11b-vision-instruct",
        required: true,
      },
      {
        key: "prompt",
        label: "Extraction Prompt",
        type: "textarea",
        defaultValue: "Extract all text from this image. Return only the raw text, preserving formatting as much as possible.",
        required: true,
      },
      {
        key: "outputFormat",
        label: "Output Format",
        type: "select",
        options: [
          { label: "Plain Text", value: "text" },
          { label: "Structured JSON", value: "json" },
          { label: "Markdown", value: "markdown" },
        ],
        defaultValue: "text",
      },
    ],
  },
  {
    type: "ai_image_analyze",
    category: "ai",
    label: "Image Analysis",
    description: "Analyze and describe image content with AI",
    icon: "🖼️",
    color: "blue",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "model",
        label: "Vision Model",
        type: "select",
        options: [
          { label: "NVIDIA LLaMA Vision 11B", value: "nvidia/llama-3.2-11b-vision-instruct" },
          { label: "NVIDIA LLaMA Vision 90B", value: "nvidia/llama-3.2-90b-vision-instruct" },
          { label: "GPT-4o Vision", value: "gpt-4o" },
        ],
        defaultValue: "nvidia/llama-3.2-11b-vision-instruct",
      },
      {
        key: "analysisType",
        label: "Analysis Type",
        type: "select",
        options: [
          { label: "General Description", value: "describe" },
          { label: "Object Detection", value: "objects" },
          { label: "Text & Document", value: "text" },
          { label: "Sentiment & Emotion", value: "emotion" },
          { label: "Custom Prompt", value: "custom" },
        ],
        defaultValue: "describe",
      },
      {
        key: "customPrompt",
        label: "Custom Prompt (if custom type)",
        type: "textarea",
        placeholder: "Describe what you see in this image...",
      },
    ],
  },

  // ── TRANSFORM NODES ──────────────────────────────────────────
  {
    type: "transform_json_parse",
    category: "transform",
    label: "JSON Parser",
    description: "Parse JSON string and extract fields",
    icon: "{ }",
    color: "orange",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "extractPath",
        label: "JSON Path (optional)",
        type: "text",
        placeholder: "data.results[0].text",
        description: "Leave empty to pass full parsed JSON",
      },
      {
        key: "onError",
        label: "On Parse Error",
        type: "select",
        options: [
          { label: "Throw Error", value: "throw" },
          { label: "Return Raw String", value: "raw" },
          { label: "Return Empty Object", value: "empty" },
        ],
        defaultValue: "throw",
      },
    ],
  },
  {
    type: "transform_text_summarize",
    category: "transform",
    label: "Text Summarizer",
    description: "Summarize long text into concise output",
    icon: "📝",
    color: "orange",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "summaryLength",
        label: "Summary Length",
        type: "select",
        options: [
          { label: "Brief (1-2 sentences)", value: "brief" },
          { label: "Short (1 paragraph)", value: "short" },
          { label: "Medium (3-5 bullet points)", value: "medium" },
          { label: "Detailed (full summary)", value: "detailed" },
        ],
        defaultValue: "medium",
      },
      {
        key: "format",
        label: "Output Format",
        type: "select",
        options: [
          { label: "Plain Text", value: "text" },
          { label: "Bullet Points", value: "bullets" },
          { label: "JSON", value: "json" },
        ],
        defaultValue: "text",
      },
      {
        key: "focus",
        label: "Focus Area (optional)",
        type: "text",
        placeholder: "Key decisions, action items, risks...",
      },
    ],
  },
  {
    type: "transform_filter",
    category: "transform",
    label: "Filter / Condition",
    description: "Filter data based on conditions",
    icon: "🔀",
    color: "orange",
    inputs: 1,
    outputs: 2,
    fields: [
      {
        key: "condition",
        label: "Condition",
        type: "select",
        options: [
          { label: "Contains text", value: "contains" },
          { label: "Does not contain", value: "not_contains" },
          { label: "Equals", value: "equals" },
          { label: "Is not empty", value: "not_empty" },
          { label: "Custom expression", value: "custom" },
        ],
        defaultValue: "not_empty",
      },
      {
        key: "value",
        label: "Compare Value",
        type: "text",
        placeholder: "Value to compare against...",
      },
      {
        key: "customExpression",
        label: "Custom Expression",
        type: "code",
        placeholder: "return input.length > 100;",
        description: "JavaScript expression. Use 'input' for the data.",
      },
    ],
  },
  {
    type: "transform_formatter",
    category: "transform",
    label: "Data Formatter",
    description: "Format and transform data structure",
    icon: "✏️",
    color: "orange",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "template",
        label: "Output Template",
        type: "textarea",
        placeholder: "Use {{input}} or {{input.field}} to reference data",
        defaultValue: "{{input}}",
        required: true,
        description: "Template with {{variable}} placeholders",
      },
    ],
  },
  {
    type: "transform_code",
    category: "transform",
    label: "Code Block",
    description: "Run custom JavaScript to transform data",
    icon: "⌨️",
    color: "orange",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "code",
        label: "JavaScript Code",
        type: "code",
        defaultValue: "// 'input' contains the previous node's output\n// Return the transformed value\nreturn input;",
        required: true,
        description: "Function body. Use 'input' to access data.",
      },
    ],
  },

  // ── INTEGRATION NODES ────────────────────────────────────────
  {
    type: "integration_github",
    category: "integration",
    label: "GitHub",
    description: "Create issues, PRs, or comments on GitHub",
    icon: "🐙",
    color: "slate",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "githubToken",
        label: "GitHub Token",
        type: "text",
        placeholder: "ghp_...",
        description: "Personal access token with 'repo' scope",
        required: true,
      },
      {
        key: "action",
        label: "Action",
        type: "select",
        options: [
          { label: "Create Issue", value: "create_issue" },
          { label: "Create Comment", value: "create_comment" },
          { label: "Create PR", value: "create_pr" },
          { label: "Get Repository Info", value: "get_repo" },
        ],
        defaultValue: "create_issue",
        required: true,
      },
      {
        key: "repo",
        label: "Repository (owner/repo)",
        type: "text",
        placeholder: "octocat/hello-world",
        required: true,
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        placeholder: "Issue/PR title or use {{input}}",
      },
      {
        key: "body",
        label: "Body",
        type: "textarea",
        placeholder: "Use {{input}} for previous node output",
        defaultValue: "{{input}}",
      },
      {
        key: "labels",
        label: "Labels (comma separated, for issues)",
        type: "text",
        placeholder: "bug, enhancement",
      },
      {
        key: "issueNumber",
        label: "Issue Number (for create_comment)",
        type: "text",
        placeholder: "42",
        description: "Leave blank to use issue_number from input",
      },
      {
        key: "head",
        label: "Head Branch (for create_pr)",
        type: "text",
        placeholder: "feature/my-branch",
        description: "Branch to merge FROM",
      },
      {
        key: "base",
        label: "Base Branch (for create_pr)",
        type: "text",
        placeholder: "main",
        defaultValue: "main",
        description: "Branch to merge INTO",
      },
    ],
  },
  {
    type: "integration_google_drive",
    category: "integration",
    label: "Google Drive",
    description: "Save files or read from Google Drive",
    icon: "📁",
    color: "blue",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "action",
        label: "Action",
        type: "select",
        options: [
          { label: "Upload File", value: "upload" },
          { label: "Create Document", value: "create_doc" },
          { label: "List Files", value: "list" },
        ],
        defaultValue: "create_doc",
        required: true,
      },
      {
        key: "folderId",
        label: "Folder ID (optional)",
        type: "text",
        placeholder: "Google Drive folder ID",
      },
      {
        key: "fileName",
        label: "File / Document Name",
        type: "text",
        placeholder: "Use {{input.title}} or fixed name",
        defaultValue: "Automation Output",
      },
      {
        key: "content",
        label: "Content",
        type: "textarea",
        defaultValue: "{{input}}",
        description: "Use {{input}} for previous node output",
      },
    ],
  },
  {
    type: "integration_gmail",
    category: "integration",
    label: "Gmail",
    description: "Send emails via Gmail",
    icon: "📧",
    color: "red",
    inputs: 1,
    outputs: 1,
    fields: [
      {
        key: "to",
        label: "To Email",
        type: "text",
        placeholder: "recipient@example.com",
        required: true,
      },
      {
        key: "subject",
        label: "Subject",
        type: "text",
        placeholder: "Email subject...",
        required: true,
      },
      {
        key: "body",
        label: "Email Body",
        type: "textarea",
        defaultValue: "{{input}}",
        description: "Use {{input}} to include previous output",
      },
      {
        key: "isHtml",
        label: "Send as HTML",
        type: "toggle",
        defaultValue: false,
      },
    ],
  },

  // ── OUTPUT NODES ─────────────────────────────────────────────
  {
    type: "output_display",
    category: "output",
    label: "Display Result",
    description: "Show output in the workflow run panel",
    icon: "📺",
    color: "purple",
    inputs: 1,
    outputs: 0,
    fields: [
      {
        key: "label",
        label: "Result Label",
        type: "text",
        placeholder: "Final Output",
        defaultValue: "Result",
      },
      {
        key: "format",
        label: "Display Format",
        type: "select",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Plain Text", value: "text" },
          { label: "JSON (formatted)", value: "json" },
          { label: "Markdown", value: "markdown" },
        ],
        defaultValue: "auto",
      },
    ],
  },
  {
    type: "output_save",
    category: "output",
    label: "Save to Storage",
    description: "Save workflow result to the database",
    icon: "💾",
    color: "purple",
    inputs: 1,
    outputs: 0,
    fields: [
      {
        key: "key",
        label: "Storage Key",
        type: "text",
        placeholder: "my-automation-result",
        required: true,
      },
      {
        key: "format",
        label: "Format",
        type: "select",
        options: [
          { label: "String", value: "string" },
          { label: "JSON", value: "json" },
        ],
        defaultValue: "string",
      },
    ],
  },
  {
    type: "output_webhook",
    category: "output",
    label: "Send Webhook",
    description: "POST result to an external URL",
    icon: "📤",
    color: "purple",
    inputs: 1,
    outputs: 0,
    fields: [
      {
        key: "url",
        label: "Webhook URL",
        type: "text",
        placeholder: "https://hooks.example.com/...",
        required: true,
      },
      {
        key: "method",
        label: "HTTP Method",
        type: "select",
        options: [
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
          { label: "PATCH", value: "PATCH" },
        ],
        defaultValue: "POST",
      },
      {
        key: "headers",
        label: "Headers (JSON)",
        type: "textarea",
        placeholder: '{"Authorization": "Bearer token"}',
      },
    ],
  },
];

export const NODE_CATEGORIES = [
  { id: "trigger", label: "Triggers", color: "emerald", description: "Start your workflow" },
  { id: "ai", label: "AI", color: "violet", description: "AI & ML models" },
  { id: "transform", label: "Transform", color: "orange", description: "Process & transform data" },
  { id: "integration", label: "Integrations", color: "blue", description: "External services" },
  { id: "output", label: "Output", color: "purple", description: "End & output nodes" },
] as const;

export const COLOR_MAP: Record<string, string> = {
  emerald: "bg-emerald-500/10 border-emerald-500/30 text-emerald-400",
  green: "bg-green-500/10 border-green-500/30 text-green-400",
  violet: "bg-violet-500/10 border-violet-500/30 text-violet-400",
  blue: "bg-blue-500/10 border-blue-500/30 text-blue-400",
  orange: "bg-orange-500/10 border-orange-500/30 text-orange-400",
  slate: "bg-slate-500/10 border-slate-500/30 text-slate-400",
  red: "bg-red-500/10 border-red-500/30 text-red-400",
  purple: "bg-purple-500/10 border-purple-500/30 text-purple-400",
};

export const GLOW_MAP: Record<string, string> = {
  emerald: "shadow-emerald-500/20",
  green: "shadow-green-500/20",
  violet: "shadow-violet-500/20",
  blue: "shadow-blue-500/20",
  orange: "shadow-orange-500/20",
  slate: "shadow-slate-500/20",
  red: "shadow-red-500/20",
  purple: "shadow-purple-500/20",
};

export function getNodeDef(type: string): AutomationNodeDef | undefined {
  return NODE_DEFINITIONS.find((n) => n.type === type);
}
