/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: [
    "react-markdown",
    "remark-gfm",
    "remark-parse",
    "unified",
    "bail",
    "is-plain-obj",
    "trough",
    "vfile",
    "vfile-message",
    "unist-util-stringify-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "unist-util-is",
    "mdast-util-from-markdown",
    "mdast-util-to-string",
    "mdast-util-gfm",
    "mdast-util-gfm-autolink-literal",
    "mdast-util-gfm-footnote",
    "mdast-util-gfm-strikethrough",
    "mdast-util-gfm-table",
    "mdast-util-gfm-task-list-item",
    "mdast-util-find-and-replace",
    "mdast-util-to-hast",
    "hast-util-to-jsx-runtime",
    "hast-util-whitespace",
    "hast-util-is-element",
    "micromark",
    "micromark-core-commonmark",
    "micromark-extension-gfm",
    "micromark-util-combine-extensions",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-character",
    "micromark-util-symbol",
    "micromark-util-types",
    "decode-named-character-reference",
    "character-entities",
    "property-information",
    "space-separated-tokens",
    "comma-separated-tokens",
    "stringify-entities",
    "zwitch",
    "rehype-highlight",
    "highlight.js",
    "devlop",
  ],
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "*.supabase.co",
        port: "",
        pathname: "/storage/v1/object/public/**",
      },
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
      },
    ],
  },
};

export default nextConfig;
