"use client";

import { useState, useCallback, useEffect } from "react";
import { ChatMessage } from "@/types";
import { createClient } from "@/lib/supabase/client";

export interface UseChatManagerOptions {
  documentId: string;
  documentType: "meeting" | "study";
  apiEndpoint: string;
  initialModelId?: "8b" | "20b";
}

export function useChatManager({
  documentId,
  documentType,
  apiEndpoint,
  initialModelId = "8b"
}: UseChatManagerOptions) {
  const [modelId, setModelId] = useState<"8b" | "20b">(initialModelId);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isHistoryLoading, setIsHistoryLoading] = useState(true);

  // 1. Fetch History on mount
  useEffect(() => {
    let mounted = true;
    const fetchHistory = async () => {
      const supabase = createClient();
      const { data, error } = await supabase
        .from("chat_messages")
        .select("*")
        .eq("document_id", documentId)
        .order("created_at", { ascending: true });

      if (mounted) {
        if (!error && data) {
          setMessages(data as ChatMessage[]);
        }
        setIsHistoryLoading(false);
      }
    };
    fetchHistory();
    return () => { mounted = false; };
  }, [documentId]);

  // 2. Submit Handle
  const handleSubmit = useCallback(async () => {
    if (!input.trim() || isLoading) return;

    // We build a temporary ID for optimistic UI
    const tempUserId = `temp-user-${Date.now()}`;
    const userMsg: ChatMessage = {
      id: tempUserId,
      user_id: "", // Optimistic, doesn't matter for rendering
      document_id: documentId,
      document_type: documentType,
      role: "user",
      content: input.trim(),
      created_at: new Date().toISOString(),
    };

    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput("");
    setIsLoading(true);

    try {
      const response = await fetch(apiEndpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        // Notice we only send `{ role, content }` formatted inside the API route if needed,
        // but our API routes currently map `messages.map((m) => ({ role: m.role, content: m.content }))` anyway.
        body: JSON.stringify({ messages: newMessages, documentId, modelId }),
      });

      if (!response.ok) throw new Error("API response error");

      const reader = response.body?.getReader();
      const decoder = new TextDecoder();
      if (!reader) throw new Error("No reader");

      const tempAssistantId = `temp-assistant-${Date.now()}`;
      const assistantMsg: ChatMessage = {
        id: tempAssistantId,
        user_id: "", 
        document_id: documentId,
        document_type: documentType,
        role: "assistant",
        content: "",
        created_at: new Date().toISOString(),
      };

      setMessages(prev => [...prev, assistantMsg]);

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunkText = decoder.decode(value, { stream: true });
        assistantMsg.content += chunkText;
        
        setMessages(prev => 
          prev.map(m => (m.id === assistantMsg.id ? { ...m, content: assistantMsg.content } : m))
        );
      }
      
      // Optional: After generation ends seamlessly, we could re-fetch the history instantly 
      // from the DB to get the TRUE database IDs generated by the API route.
      // E.g.
      const supabase = createClient();
      const { data } = await supabase
        .from("chat_messages")
        .select("*")
        .eq("document_id", documentId)
        .order("created_at", { ascending: true });
        
      if (data) setMessages(data as ChatMessage[]);

    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  }, [input, isLoading, messages, documentId, documentType, apiEndpoint, modelId]);

  return {
    messages,
    input,
    setInput,
    isLoading,
    isHistoryLoading,
    modelId,
    setModelId,
    handleSubmit
  };
}
